### ISSUE TITLE
How to calculate face's direction from a image?

### ISSUE THREAD

**Issue by mrbulb** [x6ud/x6ud.github.io#14]
Thank you for your great project for searching image :smile: May I ask how to calculate face's direction from a image? Did you use some AI model?

**Comment by x6ud** [comment]
There should be some ready-made models for human photos though

**Comment by mrbulb** [comment]
Wow, that's a large amount of work for you. Thank you for your great work again :smile:

**Comment by schroef** [comment]
How can it compare the rotation from the 3d model and then compare that to an actual database of images? I looked a vit at the code and saw you get all the data from the 3d model viewer. Then using database from Flickr and unsplash using an API key, to get images. Did not find yet how you use the search input from model vs the actual images. I'm baffled about well this works. Awesome work!
