### ISSUE TITLE
Non-Minified/Webpack'd code in repo

### ISSUE THREAD

**Issue by xrabohrok** [x6ud/x6ud.github.io#2]
I would love to help contribute code, make additions, etc, but right now I would have to de-compile the web-pack and anything else going on.  That would also make it harder for you to just merge code back into your code base.

This is a neat tool, and I think it would be cool if we could add extra species and humans to the list.  We can help, we just need access to the code before the Javascript tools enter the picture.

**Comment by x6ud** [comment]
https://github.com/x6ud/search-photos-by-model-tool
Thank you. I uploaded it.
