### ISSUE TITLE
Automating image theft?

### ISSUE THREAD

**Issue by scanlime** [x6ud/x6ud.github.io#3]
What good is a search tool that doesn't link back to the original image, author, and license information? I can see how it would be useful for artistic reference, but wouldn't you want to know where your references images come from? Isn't it very easily to steal images either intentionally or unintentionally and very hard to use them with respect to the original authors?

**Comment by nguyenlamlll** [comment]
You can view the original picture on Flickr by clicking at the picture to enlarge it. Then, there is a link on the top right called "Click here for more information about this picture". :)

![image](https://user-images.githubusercontent.com/20963684/57517199-7df7be00-7340-11e9-9bf8-7325617bad5d.png)

**Comment by scanlime** [comment]
Ah, it took me ages to notice that link, sorry. The "all rights reserved" in the example you posted is actually much larger.

**Comment by Dapid** [comment]
I would suggest making the button a bit more visible. Obviously, not everybody saw it.

Other than that, I just want to congratulate you, this tool is amazing!
